/**
 * Orchestra Mode
 *
 * Two-mode structured workflow:
 *
 * INIT mode: Takes a complex project description and creates:
 *   - ROADMAP.md — phased task breakdown with status markers
 *   - WORK_LOG.md — empty log ready for entries
 *   - Any other scaffold docs the project needs
 *   All delivered as a PR.
 *
 * RUN mode: Picks up the next task from ROADMAP.md (or a specific one):
 *   - Reads the roadmap to find the next uncompleted task
 *   - Implements the task
 *   - Creates a PR with code changes + updated ROADMAP.md + WORK_LOG.md entry
 */

import { getModel } from '../openrouter/models';

// Orchestra task entry stored in R2
export interface OrchestraTask {
  taskId: string;
  timestamp: number;
  modelAlias: string;
  repo: string;            // owner/repo
  mode: 'init' | 'run' | 'redo';
  prompt: string;          // Original user prompt (truncated)
  branchName: string;      // Branch created
  durationMs?: number;     // Execution duration in milliseconds
  prUrl?: string;          // PR URL if created
  status: 'started' | 'completed' | 'failed';
  filesChanged: string[];  // List of file paths touched
  summary?: string;        // AI-generated summary of what was done
}

// Per-user orchestra history stored in R2
export interface OrchestraHistory {
  userId: string;
  tasks: OrchestraTask[];
  updatedAt: number;
}

const MAX_HISTORY_TASKS = 30;

// Repo health check thresholds — files above these limits should be split
// before the bot attempts modifications
export const LARGE_FILE_THRESHOLD_LINES = 500;
export const LARGE_FILE_THRESHOLD_KB = 30;
// Warning zone: files approaching the threshold get flagged in the roadmap
// so splitting is planned before they become blockers
export const LARGE_FILE_WARNING_LINES = 400;

// Common file names the model should look for as existing roadmaps
const ROADMAP_FILE_CANDIDATES = [
  'ROADMAP.md',
  'roadmap.md',
  'TODO.md',
  'todo.md',
  'docs/ROADMAP.md',
  'docs/roadmap.md',
  'docs/status.md',
  '.github/ROADMAP.md',
];

// ============================================================
// INIT MODE — Create roadmap + scaffold from project description
// ============================================================

/**
 * Build the system prompt for /orchestra init.
 * Instructs the model to analyze a project description and produce
 * a ROADMAP.md + WORK_LOG.md as a PR.
 */
export function buildInitPrompt(params: {
  repo: string;
  modelAlias: string;
  branchSlug?: string; // Pre-generated branch slug (without bot/ prefix)
}): string {
  const { repo, modelAlias, branchSlug } = params;
  const [owner, repoName] = repo.split('/');
  const branch = branchSlug || `roadmap-init-${modelAlias}`;

  return `# Orchestra INIT Mode — Project Roadmap Creation

You are creating a structured project roadmap. Follow this workflow precisely.

## Target Repository
- Owner: ${owner}
- Repo: ${repoName}
- Full: ${repo}

## Workflow

### Step 1: UNDERSTAND THE REPO (max 5-8 file reads)
**Be efficient — read only what you need, then move to Step 3 quickly.**
- Use \`github_list_files\` to scan the root and main source directory
- Use \`github_read_file\` to read ONLY these key files:
  - README.md (project overview)
  - package.json or equivalent (dependencies, scripts)
  - Any existing roadmap: ${ROADMAP_FILE_CANDIDATES.join(', ')}
  - 1-2 main source files (entry point, main component)
- Do NOT read every file — the listing gives you enough structure info

### Step 1.5: FLAG LARGE FILES
- Note file sizes from the listing to flag large files (>${LARGE_FILE_THRESHOLD_LINES} lines or ~${LARGE_FILE_THRESHOLD_KB}KB)
- Also flag files in the WARNING ZONE: ${LARGE_FILE_WARNING_LINES}-${LARGE_FILE_THRESHOLD_LINES} lines. These will cross the threshold once new features are added.
- Only check source code files (.ts, .tsx, .js, .jsx, .py, .vue, .svelte, etc.) — skip config, generated, and lock files
- If any large or warning-zone files are found, they MUST be split into smaller modules before other tasks modify them
- Record which files are large and what they contain (e.g., "src/App.tsx — 800 lines, contains routing + all page components")

### Step 2: ANALYZE THE PROJECT REQUEST
- Read the user's project description carefully
- Break it down into concrete, implementable phases
- Each phase should have 2-5 specific tasks
- Order tasks by dependency (foundations first)

### Step 3: CREATE ROADMAP.md
Write a \`ROADMAP.md\` file with this exact format:

\`\`\`markdown
# Project Roadmap

> Auto-generated by Orchestra Mode | Model: ${modelAlias} | {date}

## Overview
{1-2 sentence project summary}

## Phases

### Phase 1: {phase name}
- [ ] **Task 1.1**: {task title}
  - Description: {what needs to be done}
  - Files: {likely files to create/modify}
  - Depends on: {none or task IDs}
- [ ] **Task 1.2**: {task title}
  ...

### Phase 2: {phase name}
- [ ] **Task 2.1**: {task title}
  ...

## Notes
{any architectural decisions, risks, or open questions}
\`\`\`

Key rules for the roadmap:
- Use \`- [ ]\` for pending tasks, \`- [x]\` for completed
- Task titles should be specific enough to act on (e.g., "Add JWT auth middleware" not "Handle auth")
- Include file hints so the next run knows where to work
- Include dependency info so tasks execute in order. Always extract leaf modules first (modules that no other modules depend on) before extracting parent modules.
- 3-6 phases is typical, each with 2-5 tasks

**CRITICAL — ATOMIC REFACTORING TASKS (prevents dead code / incomplete splits):**
When a task involves moving code from one file to new module files, the ENTIRE move (create new file + add imports + DELETE from source) MUST be ONE task. NEVER split "create modules" and "update source file" into separate tasks — the bot will only do the additive half and leave dead code.

BAD (causes failures — bot creates files but never deletes from source):
\`\`\`
- [ ] **Refactor 1.1**: Split App.jsx into modules
- [ ] **Refactor 1.2**: Extract financial calculations (Depends on: 1.1)
- [ ] **Refactor 1.3**: Extract destination data (Depends on: 1.1)
\`\`\`

GOOD (each task is self-contained and independently verifiable):
\`\`\`
- [ ] **Refactor 1.1**: Extract utility functions from App.jsx → src/utils.js
  - Create src/utils.js with: clamp(), fmt(), fmtUsd(), shortTax() (~lines 20-33)
  - Add import to App.jsx, DELETE these functions from App.jsx
  - Verify: grep for "function clamp" returns 0 in App.jsx, App.jsx drops by ~14 lines
- [ ] **Refactor 1.2**: Extract destination data from App.jsx → src/destinations.js
  - Create src/destinations.js with: INITIAL_DESTS array (~lines 34-267)
  - Add import to App.jsx, DELETE the INITIAL_DESTS definition from App.jsx
  - Verify: grep for "INITIAL_DESTS =" returns 0 in App.jsx, App.jsx drops by ~234 lines
  - Depends on: Refactor 1.1
\`\`\`

Rules for refactoring tasks:
1. **Use the word "DELETE"** — never say "modify" or "update" for code removal. Say "DELETE function Foo from App.jsx" or "DELETE the INITIAL_DESTS definition"
2. **Each task = create + import + DELETE** — all three actions in ONE task, ONE PR
3. **Anchor on function/const/component NAMES as primary identifiers** — e.g., "clamp(), fmt(), fmtUsd(), shortTax()". Include approximate line numbers only as a rough guide (e.g., "~lines 20-33") since line numbers shift after each extraction. The executor MUST locate code by name/signature, not line number.
4. **Include a verification gate** — grep-based checks proving the code is gone (e.g., "grep for 'function clamp' returns 0 in App.jsx") plus expected line count drop as a secondary check
5. **No deferred deletion** — never write "Depends on: X" where X is supposed to do the deletion later. Each task cleans up after itself.
6. **One extraction per task** — don't combine multiple unrelated extractions. Each task extracts ONE logical group.
7. **Topological extraction order** — extract leaf dependencies first (pure utility functions, data constants), then UI atoms, then components that import from those atoms. Never extract a component before its dependencies have been extracted. This prevents broken imports during multi-step splits.
8. **List ALL cross-file references** — if other files import/reference the extracted code, the task MUST update those files' imports to point at the new module. List them explicitly: "Update imports in Header.jsx, Dashboard.jsx to import from new module."
9. **React/hooks: preserve context and dependencies** — when extracting components or hooks, ensure ALL required imports (useState, useEffect, context), prop types, and hook dependencies are copied to the new file. After extraction, the component must receive the same props/context it had inline.

- **CRITICAL — Large file splitting:** If Step 1.5 found any large files (>${LARGE_FILE_THRESHOLD_LINES} lines) OR warning-zone files (>${LARGE_FILE_WARNING_LINES} lines), add self-contained extraction tasks EARLY in the roadmap (Phase 1 or as the first tasks in the phase that would modify the file). All tasks that modify that file MUST depend on the extraction tasks. Files in the warning zone WILL cross the threshold once features are added — split them proactively.
  **For splitting:** use \`github_create_pr\` with BOTH the new module files (action "create") AND the updated source file (action "update" or "patch") in a SINGLE PR call. The identifier check allows splits when moved identifiers are found in other files in the same PR.

### Step 4: CREATE or UPDATE WORK_LOG.md
**CRITICAL — WORK_LOG.md is APPEND-ONLY and FORMAT-PRESERVING:**
- If WORK_LOG.md already exists, use \`github_read_file\` to get its current content first
- **PRESERVE THE EXISTING TABLE FORMAT** — do NOT change column headers or restructure existing rows
- KEEP ALL existing rows BYTE-FOR-BYTE identical — do NOT reformat, reorder columns, or re-encode characters
- APPEND your new row at the bottom of the table, matching the EXISTING column format exactly
- For your new row: fill in columns that match what you have (date, task, branch, status, etc.) — leave others as "-" if the column doesn't apply
- If the file doesn't exist, create it with this template:

\`\`\`markdown
# Work Log

> Orchestra task execution history for ${repo}

| Date | Task | Model | Branch | PR | Status |
|------|------|-------|--------|-----|--------|
| {date} | Roadmap creation | ${modelAlias} | {branch} | {pr} | ✅ |
\`\`\`

### Step 5: CREATE PR
- Include both ROADMAP.md and WORK_LOG.md in the PR
- If existing files were found, use action "update" and preserve ALL existing content (especially work log rows)
- If creating new files, use action "create"
- Branch: \`${branch}\` (bot/ prefix added automatically)
- PR title: "feat: initialize project roadmap [${modelAlias}]"
- PR body: include the full roadmap content as preview, and a footer line: "Generated by: ${modelAlias}"
- Commit messages MUST include the model alias, e.g.: "feat: initialize project roadmap [${modelAlias}]"

### Step 5.5: VERIFY PR CREATION
**CRITICAL** — After calling \`github_create_pr\`, CHECK THE TOOL RESULT:
- If it returned a PR URL (https://github.com/...) → success, proceed to Step 6
- If it returned an error (422, 403, etc.) → FIX AND RETRY with a different branch name
- If it returned "AUDIT TRAIL VIOLATION" → you modified existing WORK_LOG.md rows. Re-read the file with \`github_read_file\`, use the EXACT content as-is (do NOT reformat or restructure the table), and ONLY append your new row at the bottom matching the existing column format.
- **NEVER claim you created a PR if the tool returned an error.**

### Step 6: REPORT
\`\`\`
ORCHESTRA_RESULT:
branch: {branch-name}
pr: {pr-url}
files: {comma-separated list of changed files}
summary: {1-2 sentence summary}
\`\`\`

The \`pr:\` field MUST be a real GitHub URL. If PR creation failed, set \`pr: FAILED\` and explain in the summary.

## Rules
- **DO NOT ask for user confirmation or permission** — execute ALL steps immediately and autonomously
- **Be FAST** — read only essential files (5-8 max), then create the PR. Do not exhaustively read every file.
- Always create a PR — never just describe what should be done
- If an existing roadmap exists, incorporate its content (don't discard previous work)
- Keep phases realistic — avoid overplanning
- Task descriptions should be actionable by a coding AI model in a single session
- You MUST produce an ORCHESTRA_RESULT: block with a real PR URL — the task is NOT complete without it`;
}

// ============================================================
// RUN MODE — Execute next task from roadmap
// ============================================================

// Shared params type for all run prompt builders
interface BuildRunPromptParams {
  repo: string;
  modelAlias: string;
  previousTasks: OrchestraTask[];
  specificTask?: string; // Optional: user-specified task instead of "next"
  branchSlug?: string; // Pre-generated branch slug (without bot/ prefix)
}

/**
 * Determine prompt complexity tier based on model capability.
 * Uses AA Intelligence Index from enrichment pipeline when available,
 * falls back to isFree + maxContext heuristic otherwise.
 */
function getPromptTier(modelAlias: string): 'minimal' | 'standard' | 'full' {
  const model = getModel(modelAlias);
  if (!model) return 'standard'; // Unknown model → safe middle ground

  // Use enrichment data when available (populated by /model enrich → R2)
  if (model.intelligenceIndex !== undefined) {
    if (model.intelligenceIndex >= 45) return 'full';     // Strong: Claude, GPT-4o, Grok
    if (model.intelligenceIndex >= 28) return 'standard'; // Mid: 70B-class, Mixtral
    return 'minimal';                                     // Weak: 32B-class
  }

  // Fallback when enrichment data isn't loaded
  if (!model.isFree) return 'full';  // Paid models are generally stronger
  if ((model.maxContext || 0) >= 200000) return 'standard';
  return 'minimal';
}

/**
 * Build the system prompt for /orchestra run.
 * Dispatches to tier-specific builders based on model capability.
 * - minimal (~900 tokens): weak/free models that drown in long prompts
 * - standard (~1500 tokens): mid-tier models that need guidance but not hand-holding
 * - full (~3500 tokens): strong models that benefit from detailed rules
 */
export function buildRunPrompt(params: BuildRunPromptParams): string {
  const tier = getPromptTier(params.modelAlias);
  console.log(`[orchestra] buildRunPrompt tier=${tier} for /${params.modelAlias}`);
  if (tier === 'minimal') return buildMinimalRunPrompt(params);
  if (tier === 'standard') return buildStandardRunPrompt(params);
  return buildFullRunPrompt(params);
}

/**
 * MINIMAL run prompt (~900 tokens).
 * For weak/free models (32B class). Stripped to bare essentials
 * with explicit guardrail mentions to avoid audit trail blocks.
 */
function buildMinimalRunPrompt(params: BuildRunPromptParams): string {
  const { repo, modelAlias, specificTask, branchSlug } = params;
  const [owner, repoName] = repo.split('/');
  const branch = branchSlug || `task-${modelAlias}`;

  const taskInstruction = specificTask
    ? `Find and execute this task: "${specificTask}"`
    : 'Find the first unchecked task `- [ ]` whose dependencies are done.';

  return `# Orchestra RUN

Execute the next task from the roadmap for **${repo}**.

## RULES (breaking these will block your PR)
- Read each file AT MOST ONCE. Never call github_read_file on the same path twice.
- WORK_LOG.md is APPEND-ONLY. Never delete or modify existing rows. Only add a new row at the bottom matching the existing column format.
- ROADMAP.md: only change your task from \`- [ ]\` to \`- [x]\`. Never delete or modify other tasks.
- Do NOT regenerate entire files from memory — use "patch" action for edits.
- Always finish with a github_create_pr call + ORCHESTRA_RESULT block. Use github_push_files to batch large changes before the PR.

## Step 1: READ ROADMAP
Use \`github_read_file\` with owner="${owner}" repo="${repoName}" to read ROADMAP.md.
Check paths: ${ROADMAP_FILE_CANDIDATES.slice(0, 3).join(', ')}. Also read WORK_LOG.md if it exists.
${taskInstruction}

## Step 2: READ RELEVANT FILES
Read only the files you need to implement the task. Stop reading when you have enough.

## Step 3: IMPLEMENT
For "patch" action: \`{"path":"file.js","action":"patch","patches":[{"find":"exact text","replace":"new text"}]}\`
For "create" action: \`{"path":"file.js","action":"create","content":"full content"}\`

### Creating files — USE WORKSPACE PATTERN (prevents timeout/streaming failures)
**ALWAYS use workspace_write_file + workspace_commit instead of github_push_files for new files:**
1. \`workspace_write_file\` — stage file A (path, content)
2. \`workspace_write_file\` — stage file B
3. \`workspace_delete_file\` — stage file removal (if needed)
4. \`workspace_commit\` — push all staged files to branch \`${branch}\` in one commit
5. \`github_create_pr\` — open PR on existing branch with ROADMAP/WORK_LOG patches

Each workspace_write_file is a tiny tool call (just path + content). No streaming risk.

**If creating ≤3 small files** (<100 lines each): ONE \`github_create_pr\` with all changes is also OK.

When splitting files: DELETE the extracted code from the original file. Do NOT rename it or leave dead code. If other files import the extracted code from the original, update their imports too.

### REFACTOR = CREATE + IMPORT + DELETE + UPDATE REFS (all four, same PR)
If a task says "split", "extract", or "move" code: CREATE the new file, ADD imports, DELETE the originals from the source file, UPDATE imports in other files that referenced the extracted code. Locate code by function/const name, not line number. Source file MUST shrink. Never defer deletion to a later task.

All calls use branch \`${branch}\` (bot/ prefix added automatically). Title ends with [${modelAlias}].
**After calling github_create_pr, CHECK THE RESULT.** If error, fix and retry.

## Step 4: REPORT
\`\`\`
ORCHESTRA_RESULT:
branch: {branch-name}
pr: {pr-url from tool result}
files: {comma-separated changed files}
summary: {one sentence}
\`\`\`

**IMPORTANT: Do NOT output a plan, outline, or list of steps. CALL the tools directly. Your first action must be a github_read_file tool call.**

Begin now. Read the roadmap first.`;
}

/**
 * STANDARD run prompt (~1500 tokens).
 * For mid-tier models (70B class). Adds patch guidance, few-shot example,
 * file splitting rules, and history context over minimal.
 */
function buildStandardRunPrompt(params: BuildRunPromptParams): string {
  const { repo, modelAlias, previousTasks, specificTask, branchSlug } = params;
  const [owner, repoName] = repo.split('/');
  const branch = branchSlug || `task-${modelAlias}`;

  const taskInstruction = specificTask
    ? `The user requested: "${specificTask}"\nFind this task in the roadmap and execute it.`
    : `Find the NEXT uncompleted task: first \`- [ ]\` whose dependencies are all \`- [x]\`.`;

  // Abbreviated history (last 3 tasks)
  let historyContext = '';
  if (previousTasks.length > 0) {
    const recent = previousTasks.slice(-3);
    const lines = recent.map(t => {
      const icon = t.status === 'completed' ? '✅' : '❌';
      return `  ${icon} "${t.prompt.substring(0, 60)}"`;
    });
    historyContext = `\n\n## Recent History\n${lines.join('\n')}\nAvoid duplicating this work.`;
  }

  return `# Orchestra RUN

Execute the next task from the roadmap for **${repo}**.

## RULES (breaking these will block your PR)
- Read each file AT MOST ONCE. Never call github_read_file on the same path twice.
- WORK_LOG.md is APPEND-ONLY. Never delete or modify existing rows. Only add a new row at the bottom matching the existing column format.
- ROADMAP.md: only change your task from \`- [ ]\` to \`- [x]\`. Never delete or modify other tasks.
- Do NOT regenerate entire files from memory — use "patch" action for edits.
- Always finish with a github_create_pr call + ORCHESTRA_RESULT block. Use github_push_files to batch large changes before the PR.

## Step 1: READ ROADMAP
Use \`github_read_file\` with owner="${owner}" repo="${repoName}" to read ROADMAP.md.
Check paths: ${ROADMAP_FILE_CANDIDATES.join(', ')}. Also read WORK_LOG.md if it exists.
${taskInstruction}

## Step 2: UNDERSTAND CODEBASE
Use \`github_list_files\` and \`github_read_file\` to read files related to the task.
If any source file exceeds ~${LARGE_FILE_WARNING_LINES} lines, you may split it as part of this task.

## Step 3: IMPLEMENT
Branch: \`${branch}\` (bot/ prefix added automatically)
Title: under 70 chars, ends with [${modelAlias}]
Body: summary + "Generated by: ${modelAlias}"

### How to edit files — USE PATCH ACTION
For existing files (especially >100 lines), use action \`"patch"\`:
1. Read the file first with github_read_file
2. Use \`{"path":"file.js","action":"patch","patches":[{"find":"exact text to find","replace":"replacement text"}]}\`
3. Each "find" must match EXACTLY once — copy text verbatim including whitespace

Only use "update" (full content) for small files (<100 lines) or when >50% of the file changes.
Use "create" for new files.

### CRITICAL: Creating files — USE WORKSPACE PATTERN (prevents streaming timeouts)
**ALWAYS use workspace_write_file + workspace_commit for creating new files:**
1. \`workspace_write_file\` — stage each new file one at a time (path, content)
2. \`workspace_delete_file\` — stage file removals (if needed)
3. \`workspace_commit\` — push ALL staged files to branch \`${branch}\` in one atomic commit
4. \`github_create_pr\` — open PR on existing branch with ROADMAP/WORK_LOG patches

Each \`workspace_write_file\` call is tiny (just the file content as a tool argument), so there's no risk of streaming timeout. The commit happens server-side with no large payloads.

**If creating ≤3 small files** (<100 lines each): one \`github_create_pr\` with all changes is also OK.

### File splitting / extraction (if task requires it)
1. Stage new module files via \`workspace_write_file\` (one call per file), then \`workspace_commit\`
2. Updated original file with action "patch" — include in final github_create_pr:
   - ADD import statements for the new modules at the top
   - DELETE the extracted code (functions, constants, components) from the original file using patches
   - Re-export from the new modules if needed for backwards compatibility
   - **DO NOT leave dead code** — the extracted code MUST be removed, not renamed or commented out

### REFACTOR TASK INTERPRETATION — CRITICAL
If a task says "split", "extract", or "move" code into a new file, you MUST do ALL FOUR in ONE PR:
1. **CREATE** the new module file with the extracted code
2. **ADD** import statements to the source file
3. **DELETE** the original definitions from the source file
4. **UPDATE** imports in any OTHER files that referenced the extracted code from the source file
Locate code to extract by **function/const/component name**, not line number (line numbers shift after prior extractions). NEVER assume deletion is deferred to a later task. The source file's line count MUST drop significantly after a split. If it barely changed, you left dead code — go back and delete the extracted definitions.
When extracting React components/hooks: copy ALL required imports (useState, useEffect, context providers), prop types, and hook dependencies to the new file.

**After calling github_create_pr, CHECK THE RESULT.** If error (422, 403), fix and retry with a different branch name. NEVER claim success if the tool returned an error.

## Step 4: REPORT
\`\`\`
ORCHESTRA_RESULT:
branch: {branch-name}
pr: {pr-url from tool result}
files: {comma-separated changed files}
summary: {one sentence}
\`\`\`

The \`pr:\` field MUST be a real GitHub URL. If PR creation failed, set \`pr: FAILED\`.
${historyContext}

**IMPORTANT: Do NOT output a plan or outline. CALL tools directly. Your first action must be a github_read_file tool call.**

Begin now. Read the roadmap first.`;
}

/**
 * FULL run prompt (~3500 tokens).
 * For strong models (Claude, GPT-4o, Grok). Complete detailed rules,
 * file splitting guidance, audit trail enforcement, verification steps.
 */
function buildFullRunPrompt(params: BuildRunPromptParams): string {
  const { repo, modelAlias, previousTasks, specificTask, branchSlug } = params;
  const [owner, repoName] = repo.split('/');
  const branch = branchSlug || `{task-slug}-${modelAlias}`;

  // Format previous task context
  let historyContext = '';
  if (previousTasks.length > 0) {
    const recent = previousTasks.slice(-5);
    const lines = recent.map(t => {
      const icon = t.status === 'completed' ? '✅' : t.status === 'failed' ? '❌' : '⏳';
      const pr = t.prUrl ? ` → ${t.prUrl}` : '';
      const sum = t.summary ? ` — ${t.summary.substring(0, 100)}` : '';
      return `  ${icon} [${t.branchName}] "${t.prompt.substring(0, 80)}"${pr}${sum}`;
    });
    historyContext = `\n\n## Recent Orchestra History\n${lines.join('\n')}\n\nAvoid duplicating work already done.`;
  }

  const taskSelection = specificTask
    ? `The user has requested a SPECIFIC task: "${specificTask}"
Find this task (or the closest match) in the roadmap and execute it.
If the task is not in the roadmap, execute it anyway and add it to the roadmap as a completed item.`
    : `Find the NEXT uncompleted task in the roadmap:
- Look for the first \`- [ ]\` item whose dependencies are all satisfied (\`- [x]\`)
- If no roadmap exists, tell the user to run \`/orchestra init\` first
- If all tasks are completed, congratulate the user and suggest next steps`;

  return `# Orchestra RUN Mode

Execute the next task from the project roadmap for **${repo}**.

## CRITICAL RULES (breaking these will block your PR)
- Read each file AT MOST ONCE. Never call github_read_file on the same path twice.
- WORK_LOG.md is APPEND-ONLY. Never delete or modify existing rows. Only add a new row at the bottom matching the existing column format.
- ROADMAP.md: only change your task from \`- [ ]\` to \`- [x]\`. Never delete or modify other tasks.
- Do NOT regenerate entire files from memory — use "patch" action for edits.
- After calling github_create_pr, CHECK THE RESULT. If it returned an error, fix and retry. Never claim success if the tool returned an error.
- Always finish with a github_create_pr call + ORCHESTRA_RESULT block with a real PR URL. Use github_push_files to batch large changes before the PR.

## Step 1: READ ROADMAP
Use \`github_read_file\` with owner="${owner}" repo="${repoName}" to read the roadmap.
Check paths: ${ROADMAP_FILE_CANDIDATES.join(', ')}. Also read WORK_LOG.md if it exists.
If no roadmap found: "No roadmap found. Run \`/orchestra init ${repo} <description>\` first."

## Step 2: SELECT TASK
${taskSelection}

## Step 3: UNDERSTAND CODEBASE
Use \`github_list_files\` and \`github_read_file\` to read files related to the task.
If any source file exceeds ~${LARGE_FILE_WARNING_LINES} lines, you can split it as part of this task.

## Step 4: IMPLEMENT

**Use "patch" action for editing existing files (especially files >100 lines):**
- Read the file first with \`github_read_file\`
- Use action \`"patch"\` with \`"patches"\` array of \`{"find":"exact text","replace":"new text"}\` pairs
- Each "find" must match exactly once — copy the EXACT text from the file including whitespace
- This prevents syntax errors, encoding changes, and unwanted rewrites that happen with "update"
- Only use "update" (full file content) for small files (<100 lines) or when changes touch >50% of the file
- Use "create" for new files

Example patch: \`{"path":"src/App.jsx","action":"patch","patches":[{"find":"const data = [...]","replace":"import { data } from './data'"}]}\`

### CRITICAL: Creating files — USE WORKSPACE PATTERN (prevents streaming timeouts)
**ALWAYS use workspace_write_file + workspace_commit for creating new files:**
1. Call \`workspace_write_file\` for EACH new file (path, content). Each call is tiny — no streaming risk.
2. Call \`workspace_delete_file\` to stage file removals (if needed).
3. Call \`workspace_commit\` ONCE to push ALL staged files to branch \`${branch}\` in one atomic commit.
4. Call \`github_create_pr\` to open the PR on the existing branch with ROADMAP/WORK_LOG patches.

This is MUCH safer than github_push_files because each workspace_write_file sends only one file as a tool argument. No giant JSON arrays, no streaming timeout risk.

**If creating ≤3 small files** (<100 lines each): one \`github_create_pr\` with all changes is also OK.

**FILE SPLITTING — How to split a large file into modules:**
1. Read the original file with \`github_read_file\`
2. Plan the split: identify logical groups of functions/components to extract
3. Stage each new module file via \`workspace_write_file\`, then \`workspace_commit\`
4. Final \`github_create_pr\`: patch the original file + ROADMAP + WORK_LOG. The patches MUST:
   - ADD import statements for the new modules at the top
   - DELETE the extracted code from the original file (remove the actual functions/constants/components that were moved)
   - Re-export from new modules if needed for backwards compatibility
   - **NEVER leave dead code** — do NOT rename extracted code to _MOVED or comment it out. DELETE it entirely.
The identifier check allows splits: identifiers moved to other files on the same branch are not counted as lost.
**CRITICAL**: The original file's line count should DROP significantly after a split. If it barely changed, you left dead code.

**REFACTOR TASK INTERPRETATION — CRITICAL (prevents the #1 bot failure mode):**
If a task says "split", "extract", "move", or "refactor" code into new files, you MUST do ALL FOUR in ONE PR:
1. **CREATE** the new module file(s) with the extracted code
2. **ADD** import statements to the source file
3. **DELETE** the original definitions (functions, constants, components, data arrays) from the source file
4. **UPDATE** imports in any OTHER files that referenced the extracted code from the source file
Locate code to extract by **function/const/component name and signature**, not line number — line numbers shift after prior extractions. Re-read the file to find the exact current location before editing.
NEVER assume deletion will happen in a later task — even if the roadmap's dependency chain suggests it. Each extraction task MUST be self-contained: create + import + delete + update refs. If the source file's line count doesn't drop substantially, the task is NOT complete.
When extracting React components/hooks: copy ALL required imports (useState, useEffect, context providers, CSS modules), prop types, and hook dependencies to the new file. The component must work identically after extraction.

**Other rules:**
- Follow existing code conventions, proper types (no \`any\`)
- Do NOT regenerate entire files from memory — you WILL introduce syntax errors and encoding changes

If blocked (API errors): update WORK_LOG.md with status, report \`pr: FAILED\`.

## Step 5: UPDATE ROADMAP & WORK LOG (in same PR)
- **ROADMAP.md**: Change ONLY your completed task from \`- [ ]\` to \`- [x]\`. Never delete tasks.
- **WORK_LOG.md**: Read the existing file first. KEEP ALL existing content BYTE-FOR-BYTE identical. APPEND a new row at the bottom matching the EXISTING column format. Do NOT restructure the table or change column headers. If the existing format differs from what you expect, match it exactly.

## Step 6: CREATE PR
- Branch: \`${branch}\` (bot/ prefix added automatically)
- Title: under 70 chars, ends with [${modelAlias}]
- Body: summary + "Generated by: ${modelAlias}"
- **Verify the tool returned a PR URL** — if error (422, 403), retry with different branch name. NEVER claim success if tool returned error.

## Step 7: REPORT
\`\`\`
ORCHESTRA_RESULT:
branch: {branch-name}
pr: {pr-url}
files: {comma-separated changed files}
summary: {1-2 sentence summary}
\`\`\`

## Rules
- **DO NOT ask for user confirmation or permission** — execute ALL steps immediately and autonomously
- Always create a PR. One task per run. Update ROADMAP.md + WORK_LOG.md in same PR.
- **USE "patch" ACTION for editing existing files** — never regenerate entire files from memory. Never delete work log entries or roadmap tasks.
- Use "${modelAlias}" in branch names and commit messages.
- You MUST produce an ORCHESTRA_RESULT: block with a real PR URL — the task is NOT complete without it
- **Do NOT output a plan, outline, or list of steps.** CALL tools directly. Your first action must be a github_read_file tool call.
${historyContext}`;
}

// ============================================================
// LEGACY: buildOrchestraPrompt (kept for backward compat)
// ============================================================

/**
 * Build the orchestra system prompt (delegates to run mode).
 * @deprecated Use buildRunPrompt or buildInitPrompt directly.
 */
export function buildOrchestraPrompt(params: {
  repo: string;
  modelAlias: string;
  previousTasks: OrchestraTask[];
}): string {
  return buildRunPrompt(params);
}

// ============================================================
// Result parsing
// ============================================================

/**
 * Parse the ORCHESTRA_RESULT block from the model's final response.
 * Returns extracted metadata or null if not found.
 */
export function parseOrchestraResult(response: string): {
  branch: string;
  prUrl: string;
  files: string[];
  summary: string;
} | null {
  // Try multiple patterns — models format this block inconsistently
  const match = response.match(/ORCHESTRA_RESULT:\s*\n([\s\S]*?)(?:```|$)/)
    || response.match(/ORCHESTRA_RESULT:\s*([\s\S]*?)(?:```|$)/)
    || response.match(/ORCHESTRA.RESULT[:\s]+([\s\S]*?)(?:```|$)/i);
  if (!match) return null;

  const block = match[1];
  // Parse each field line-by-line to avoid cross-line matching
  const lines = block.split('\n');
  let branch = '';
  let prUrl = '';
  let filesLine = '';
  let summary = '';

  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.startsWith('branch:')) {
      branch = trimmed.slice('branch:'.length).trim();
    } else if (trimmed.startsWith('pr:')) {
      prUrl = trimmed.slice('pr:'.length).trim();
    } else if (trimmed.startsWith('files:')) {
      filesLine = trimmed.slice('files:'.length).trim();
    } else if (trimmed.startsWith('summary:')) {
      summary = trimmed.slice('summary:'.length).trim();
    }
  }

  const files = filesLine
    .split(',')
    .map(f => f.trim())
    .filter(Boolean);

  if (!branch && !prUrl) return null;

  // Validate prUrl looks like a real URL — reject "attempted", "failed", placeholders
  const validPrUrl = prUrl.startsWith('https://') ? prUrl : '';

  return { branch, prUrl: validPrUrl, files, summary };
}

/**
 * Cross-reference a parsed orchestra result against tool output evidence.
 * Detects phantom PRs: model claims a PR URL but tool results show failures.
 *
 * @param result - Parsed orchestra result (from parseOrchestraResult)
 * @param fullOutput - The full task output including tool results
 * @returns Validated result with prUrl cleared if evidence contradicts the claim
 */
export function validateOrchestraResult(
  result: { branch: string; prUrl: string; files: string[]; summary: string },
  fullOutput: string,
): { branch: string; prUrl: string; files: string[]; summary: string; phantomPr: boolean } {
  if (!result.prUrl) {
    return { ...result, phantomPr: false };
  }

  // Evidence of github_create_pr failure in tool results
  const prFailurePatterns = [
    'PR NOT CREATED',
    'github_create_pr FAILED',
    'Destructive update blocked',
    'Full-rewrite blocked',
    'INCOMPLETE REFACTOR blocked',
    'DATA FABRICATION blocked',
    'NET DELETION blocked',
    'AUDIT TRAIL VIOLATION',
    'ROADMAP TAMPERING blocked',
    'FALSE COMPLETION blocked',
    'Error executing github_create_pr',
  ];

  const hasFailureEvidence = prFailurePatterns.some(pattern => fullOutput.includes(pattern));

  // Evidence of actual PR creation success
  // The tool returns "Pull Request created successfully!" + "PR: https://github.com/..."
  const hasSuccessEvidence =
    fullOutput.includes('Pull Request created successfully') ||
    fullOutput.includes(`PR: ${result.prUrl}`) ||
    fullOutput.includes(`"html_url":"${result.prUrl}"`);

  // If there's failure evidence AND no success evidence, this is a phantom PR
  if (hasFailureEvidence && !hasSuccessEvidence) {
    console.log(`[orchestra] Phantom PR detected: model claimed ${result.prUrl} but tool results show failure`);
    return {
      ...result,
      prUrl: '',
      summary: `⚠️ PHANTOM PR: Model claimed PR but github_create_pr failed. ${result.summary}`,
      phantomPr: true,
    };
  }

  return { ...result, phantomPr: false };
}

// ============================================================
// Helpers
// ============================================================

/**
 * Generate a URL-safe task slug from a prompt.
 * Example: "Add dark mode toggle" → "add-dark-mode-toggle"
 */
export function generateTaskSlug(prompt: string): string {
  return prompt
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .substring(0, 40)
    .replace(/-+$/, '');
}

/**
 * Parse the /orchestra command arguments.
 *
 * Formats:
 *   /orchestra init owner/repo <project description>
 *   /orchestra run owner/repo [specific task]
 *   /orchestra history
 *   /orchestra owner/repo <prompt>  (legacy, treated as run)
 */
export function parseOrchestraCommand(args: string[]): {
  mode: 'init' | 'run';
  repo: string;
  prompt: string;
} | null {
  if (args.length < 2) return null;

  const first = args[0].toLowerCase();

  // /orchestra init owner/repo <description>
  if (first === 'init') {
    if (args.length < 3) return null;
    const repo = args[1];
    if (!isValidRepo(repo)) return null;
    const prompt = args.slice(2).join(' ').trim();
    if (!prompt) return null;
    return { mode: 'init', repo, prompt };
  }

  // /orchestra run owner/repo [specific task]
  if (first === 'run') {
    if (args.length < 2) return null;
    const repo = args[1];
    if (!isValidRepo(repo)) return null;
    // Prompt is optional for run mode (defaults to "next task")
    const prompt = args.length > 2 ? args.slice(2).join(' ').trim() : '';
    return { mode: 'run', repo, prompt };
  }

  // Legacy: /orchestra owner/repo <prompt> (treated as run)
  const repo = args[0];
  if (!isValidRepo(repo)) return null;
  const prompt = args.slice(1).join(' ').trim();
  if (!prompt) return null;
  return { mode: 'run', repo, prompt };
}

/** Validate owner/repo format */
function isValidRepo(repo: string): boolean {
  return /^[a-zA-Z0-9_.-]+\/[a-zA-Z0-9_.-]+$/.test(repo);
}

// ============================================================
// R2 History Management
// ============================================================

/**
 * Load orchestra history from R2.
 */
export async function loadOrchestraHistory(
  r2: R2Bucket,
  userId: string
): Promise<OrchestraHistory | null> {
  const key = `orchestra/${userId}/history.json`;
  try {
    const obj = await r2.get(key);
    if (!obj) return null;
    return await obj.json() as OrchestraHistory;
  } catch {
    return null;
  }
}

/**
 * Store an orchestra task entry in R2 history.
 */
export async function storeOrchestraTask(
  r2: R2Bucket,
  userId: string,
  task: OrchestraTask
): Promise<void> {
  const key = `orchestra/${userId}/history.json`;

  let history: OrchestraHistory;
  try {
    const obj = await r2.get(key);
    if (obj) {
      history = await obj.json() as OrchestraHistory;
    } else {
      history = { userId, tasks: [], updatedAt: Date.now() };
    }
  } catch {
    history = { userId, tasks: [], updatedAt: Date.now() };
  }

  history.tasks.push(task);

  // Keep only the most recent tasks
  if (history.tasks.length > MAX_HISTORY_TASKS) {
    history.tasks = history.tasks.slice(-MAX_HISTORY_TASKS);
  }

  history.updatedAt = Date.now();
  await r2.put(key, JSON.stringify(history));
}

/** Threshold for marking a "started" task as stale (30 minutes). */
const STALE_TASK_THRESHOLD_MS = 30 * 60 * 1000;

/**
 * Clean up stale tasks in a user's orchestra history.
 * Tasks stuck in "started" status for more than 30 minutes are marked as "failed".
 * Returns the number of tasks cleaned up.
 */
export async function cleanupStaleTasks(
  r2: R2Bucket,
  userId: string,
  now: number = Date.now()
): Promise<number> {
  const key = `orchestra/${userId}/history.json`;

  let history: OrchestraHistory;
  try {
    const obj = await r2.get(key);
    if (!obj) return 0;
    history = await obj.json() as OrchestraHistory;
  } catch {
    return 0;
  }

  let cleaned = 0;
  for (const task of history.tasks) {
    if (task.status === 'started' && (now - task.timestamp) > STALE_TASK_THRESHOLD_MS) {
      task.status = 'failed';
      task.summary = `STALE: Task stuck in "started" for >${Math.round((now - task.timestamp) / 60000)}min — auto-failed`;
      cleaned++;
    }
  }

  if (cleaned > 0) {
    history.updatedAt = now;
    await r2.put(key, JSON.stringify(history));
  }

  return cleaned;
}

// ============================================================
// Historical Model Performance Stats
// ============================================================

/** Per-model completion stats derived from orchestra history. */
export interface ModelCompletionStats {
  alias: string;
  completed: number;
  failed: number;
  total: number;
  /** Bayesian-smoothed success rate (0-1). Starts at 0.5 with 2 pseudo-observations. */
  successRate: number;
}

/**
 * Compute per-model completion stats from all users' orchestra histories.
 * Uses a Bayesian prior (Beta(1,1) → start at 50% with 2 pseudo-obs) so that
 * models with few tasks don't dominate the ranking.
 */
export function getModelCompletionStats(
  histories: OrchestraHistory[]
): Map<string, ModelCompletionStats> {
  const raw = new Map<string, { completed: number; failed: number }>();

  for (const history of histories) {
    for (const task of history.tasks) {
      if (task.status !== 'completed' && task.status !== 'failed') continue;
      const entry = raw.get(task.modelAlias) ?? { completed: 0, failed: 0 };
      if (task.status === 'completed') entry.completed++;
      else entry.failed++;
      raw.set(task.modelAlias, entry);
    }
  }

  const stats = new Map<string, ModelCompletionStats>();
  for (const [alias, { completed, failed }] of raw) {
    const total = completed + failed;
    // Beta(1,1) prior → (completed + 1) / (total + 2)
    const successRate = (completed + 1) / (total + 2);
    stats.set(alias, { alias, completed, failed, total, successRate });
  }
  return stats;
}

/**
 * Load all orchestra histories from R2 for model stats aggregation.
 * Scans the orchestra/ prefix and loads all history.json files.
 * Returns at most 50 histories to bound R2 reads.
 */
export async function loadAllOrchestraHistories(
  r2: R2Bucket
): Promise<OrchestraHistory[]> {
  const histories: OrchestraHistory[] = [];
  try {
    const listed = await r2.list({ prefix: 'orchestra/', limit: 100 });
    const historyKeys = listed.objects
      .filter(o => o.key.endsWith('/history.json'))
      .slice(0, 50);

    for (const obj of historyKeys) {
      try {
        const data = await r2.get(obj.key);
        if (data) {
          histories.push(await data.json() as OrchestraHistory);
        }
      } catch { /* skip corrupt entries */ }
    }
  } catch { /* R2 unavailable — return empty */ }
  return histories;
}

/**
 * Format orchestra history for display to the user.
 */
export function formatOrchestraHistory(history: OrchestraHistory | null): string {
  if (!history || history.tasks.length === 0) {
    return '📋 No orchestra tasks yet.\n\nUsage:\n  /orchestra init owner/repo <project description>\n  /orchestra run owner/repo';
  }

  const lines: string[] = ['📋 Orchestra Task History\n'];

  for (const task of history.tasks.slice(-10).reverse()) {
    const status = task.status === 'completed' ? '✅' : task.status === 'failed' ? '❌' : '⏳';
    const date = new Date(task.timestamp).toLocaleDateString();
    const modeTag = task.mode === 'init' ? ' [INIT]' : task.mode === 'redo' ? ' [REDO]' : '';
    const duration = task.durationMs
      ? ` | ⏱ ${task.durationMs >= 60000 ? `${Math.round(task.durationMs / 60000)}m` : `${Math.round(task.durationMs / 1000)}s`}`
      : '';
    const pr = task.prUrl ? `\n   PR: ${task.prUrl}` : '';
    const summary = task.summary ? `\n   ${task.summary}` : '';
    lines.push(
      `${status} ${task.repo}${modeTag} — ${task.prompt.substring(0, 60)}${task.prompt.length > 60 ? '...' : ''}` +
      `\n   🤖 /${task.modelAlias} | 🌿 ${task.branchName} | ${date}${duration}${pr}${summary}`
    );
  }

  return lines.join('\n\n');
}

// ============================================================
// Roadmap Status Display
// ============================================================

/**
 * Fetch the roadmap file from a GitHub repo.
 * Tries ROADMAP_FILE_CANDIDATES in order and returns the first found.
 */
export async function fetchRoadmapFromGitHub(
  owner: string,
  repo: string,
  githubToken?: string
): Promise<{ content: string; path: string }> {
  const headers: Record<string, string> = {
    'User-Agent': 'MoltworkerBot/1.0',
    'Accept': 'application/vnd.github.v3+json',
  };
  if (githubToken) {
    headers['Authorization'] = `Bearer ${githubToken}`;
  }

  for (const candidate of ROADMAP_FILE_CANDIDATES) {
    const url = `https://api.github.com/repos/${owner}/${repo}/contents/${candidate}`;
    const response = await fetch(url, { headers });
    if (!response.ok) continue;

    const data = await response.json() as { content?: string; message?: string };
    if (!data.content) continue;

    // Decode base64 → UTF-8 (atob produces Latin-1, mangling multi-byte chars like →)
    const binary = atob(data.content.replace(/\n/g, ''));
    const bytes = Uint8Array.from(binary, c => c.charCodeAt(0));
    const content = new TextDecoder().decode(bytes);
    return { content, path: candidate };
  }

  throw new Error('No roadmap file found. Run `/orch init` to create one.');
}

/** Parsed phase from a roadmap */
interface RoadmapPhase {
  name: string;
  tasks: { title: string; done: boolean }[];
}

/**
 * Parse a ROADMAP.md into phases and tasks.
 *
 * Supports multiple formats:
 * - Standard: `### Phase N: Title` headers + `- [x]` task lines
 * - H2 headers: `## Phase N: Title` or `## Title`
 * - Numbered lists: `1. [x] Task title` or `1. Task title` (treated as done=false)
 * - Indented checkboxes: `  - [x] Task title` (up to 4 spaces / 1 tab indent)
 * - Flat checklists: `- [x] Task` with no phase headers (grouped into "Tasks")
 */
export function parseRoadmapPhases(content: string): RoadmapPhase[] {
  const phases: RoadmapPhase[] = [];
  let current: RoadmapPhase | null = null;

  for (const line of content.split('\n')) {
    // Match phase headers:
    // "### Phase 1: Setup", "### Phase 1 — Setup", "### Setup" (any ### header)
    // "## Phase 1: Setup", "## Step 1: Setup", "## Setup" (any ## header)
    // "# Phase 1: Setup", "# Step 1 — Setup" (single # with Phase/Step/Sprint prefix only)
    const phaseMatch = line.match(/^###\s+(?:Phase\s+\d+\s*[:.—\-]\s*)?(.+)/i)
      || line.match(/^##\s+(?:(?:Phase|Step|Sprint)\s+\d+\s*[:.—\-]\s*)?(.+)/i)
      || line.match(/^#\s+(?:Phase|Step|Sprint)\s+\d+\s*[:.—\-]\s*(.+)/i);
    if (phaseMatch) {
      current = { name: phaseMatch[1].trim(), tasks: [] };
      phases.push(current);
      continue;
    }

    // Match task lines (with optional leading whitespace up to 4 spaces or 1 tab):
    // "- [x] Task", "* [ ] Task", "  - [x] Task", "\t- [ ] Task"
    const taskMatch = line.match(/^[\t ]{0,4}[-*]\s+\[([ xX])\]\s+(.+)/);
    if (taskMatch) {
      const done = taskMatch[1].toLowerCase() === 'x';
      const title = taskMatch[2]
        .replace(/^\*\*(?:Task\s+[\d.]+)?\*\*:?\s*/, '')
        .trim();
      // If no phase header was seen yet, create a default "Tasks" phase
      if (!current) {
        current = { name: 'Tasks', tasks: [] };
        phases.push(current);
      }
      current.tasks.push({ title, done });
      continue;
    }

    // Match numbered list items with checkboxes: "1. [x] Task title"
    const numberedCheckboxMatch = line.match(/^[\t ]{0,4}\d+\.\s+\[([ xX])\]\s+(.+)/);
    if (numberedCheckboxMatch) {
      const done = numberedCheckboxMatch[1].toLowerCase() === 'x';
      const title = numberedCheckboxMatch[2]
        .replace(/^\*\*(?:Task\s+[\d.]+)?\*\*:?\s*/, '')
        .trim();
      if (!current) {
        current = { name: 'Tasks', tasks: [] };
        phases.push(current);
      }
      current.tasks.push({ title, done });
      continue;
    }

    // Match plain numbered list items (no checkbox, treated as not done): "1. Task title"
    // Only match if we're already inside a phase (to avoid matching random numbered text)
    const numberedPlainMatch = line.match(/^[\t ]{0,4}\d+\.\s+(.+)/);
    if (numberedPlainMatch && current) {
      const title = numberedPlainMatch[1]
        .replace(/^\*\*(?:Task\s+[\d.]+)?\*\*:?\s*/, '')
        .trim();
      // Skip lines that look like sub-descriptions (start with lowercase, very short)
      if (title.length > 5) {
        current.tasks.push({ title, done: false });
      }
    }
  }

  return phases.filter(phase => phase.tasks.length > 0);
}

/**
 * Format roadmap content into a concise status display for Telegram.
 * Shows per-phase progress with task checkmarks.
 */
export function formatRoadmapStatus(content: string, repo: string, filePath: string): string {
  const phases = parseRoadmapPhases(content);

  if (phases.length === 0) {
    // No structured phases found — show raw content (truncated)
    const preview = content.length > 3000 ? content.slice(0, 3000) + '\n\n[Truncated]' : content;
    return `📋 Roadmap — ${repo}\n📄 ${filePath}\n\n${preview}`;
  }

  const lines: string[] = [`📋 Roadmap Status — ${repo}`];
  lines.push(`📄 ${filePath}\n`);

  let totalDone = 0;
  let totalTasks = 0;

  for (const phase of phases) {
    const done = phase.tasks.filter(t => t.done).length;
    const total = phase.tasks.length;
    totalDone += done;
    totalTasks += total;

    const phaseDone = total > 0 && done === total;
    const phaseIcon = phaseDone ? '✅' : done > 0 ? '🔨' : '⏳';
    lines.push(`${phaseIcon} ${phase.name} (${done}/${total})`);

    for (const task of phase.tasks) {
      lines.push(`  ${task.done ? '✅' : '⬜'} ${task.title}`);
    }
    lines.push('');
  }

  // Overall progress bar
  const pct = totalTasks > 0 ? Math.round((totalDone / totalTasks) * 100) : 0;
  const filled = Math.round(pct / 10);
  const bar = '█'.repeat(filled) + '░'.repeat(10 - filled);
  lines.push(`━━━ Overall: ${totalDone}/${totalTasks} tasks (${pct}%)`);
  lines.push(`[${bar}]`);

  return lines.join('\n');
}

// ============================================================
// Roadmap Reset / Redo
// ============================================================

/**
 * Find tasks in roadmap content that match a query string.
 * Matches against task titles (case-insensitive, substring match).
 * Also matches "Phase N" to select all tasks in a phase.
 */
export function findMatchingTasks(
  content: string,
  query: string
): { lineIndex: number; title: string; done: boolean; phase: string }[] {
  const matches: { lineIndex: number; title: string; done: boolean; phase: string }[] = [];
  const queryLower = query.toLowerCase().trim();
  const lines = content.split('\n');

  // Check if the query targets a whole phase (e.g. "Phase 2" or "phase 2")
  const phaseQuery = queryLower.match(/^phase\s+(\d+)$/i);

  let currentPhase = '';
  let currentPhaseNum = 0;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    // Track current phase
    const phaseMatch = line.match(/^###\s+(?:Phase\s+(\d+)[:.—-]\s*)?(.+)/i);
    if (phaseMatch) {
      currentPhaseNum = phaseMatch[1] ? parseInt(phaseMatch[1], 10) : currentPhaseNum + 1;
      currentPhase = phaseMatch[2]?.trim() || `Phase ${currentPhaseNum}`;
      continue;
    }

    // Match task lines
    const taskMatch = line.match(/^[-*]\s+\[([ xX])\]\s+(.+)/);
    if (taskMatch && currentPhase) {
      const done = taskMatch[1].toLowerCase() === 'x';
      const rawTitle = taskMatch[2]
        .replace(/^\*\*(?:Task\s+[\d.]+)?\*\*:?\s*/, '')
        .trim();

      // Check if this task matches the query
      const titleLower = rawTitle.toLowerCase();
      const fullLineLower = line.toLowerCase();

      if (phaseQuery) {
        // Phase-level match: select all tasks in the matching phase
        if (currentPhaseNum === parseInt(phaseQuery[1], 10)) {
          matches.push({ lineIndex: i, title: rawTitle, done, phase: currentPhase });
        }
      } else if (
        titleLower.includes(queryLower) ||
        fullLineLower.includes(queryLower)
      ) {
        matches.push({ lineIndex: i, title: rawTitle, done, phase: currentPhase });
      }
    }
  }

  return matches;
}

/**
 * Reset (uncheck) matching tasks in roadmap content.
 * Returns modified content and info about what was reset.
 */
export function resetRoadmapTasks(
  content: string,
  query: string
): { modified: string; resetCount: number; taskNames: string[] } {
  const matches = findMatchingTasks(content, query);

  // Only reset tasks that are currently done
  const toReset = matches.filter(m => m.done);

  if (toReset.length === 0) {
    return { modified: content, resetCount: 0, taskNames: [] };
  }

  const lines = content.split('\n');
  const taskNames: string[] = [];

  for (const match of toReset) {
    // Replace [x] or [X] with [ ]
    lines[match.lineIndex] = lines[match.lineIndex].replace(/\[([xX])\]/, '[ ]');
    taskNames.push(match.title);
  }

  return {
    modified: lines.join('\n'),
    resetCount: toReset.length,
    taskNames,
  };
}

/**
 * Create a GitHub PR that resets roadmap task checkboxes.
 * Uses the GitHub Git Data API (same pattern as github_create_pr tool).
 */
export async function createRoadmapResetPR(params: {
  owner: string;
  repo: string;
  filePath: string;
  newContent: string;
  taskNames: string[];
  githubToken: string;
}): Promise<{ prUrl: string; branch: string }> {
  const { owner, repo, filePath, newContent, taskNames, githubToken } = params;

  const headers: Record<string, string> = {
    'User-Agent': 'MoltworkerBot/1.0',
    'Accept': 'application/vnd.github.v3+json',
    'Authorization': `Bearer ${githubToken}`,
    'Content-Type': 'application/json',
  };

  const apiBase = `https://api.github.com/repos/${owner}/${repo}`;
  const branchName = `bot/roadmap-reset-${Date.now()}`;

  // Step 1: Get base branch SHA
  const refResponse = await fetch(`${apiBase}/git/ref/heads/main`, { headers });
  if (!refResponse.ok) {
    throw new Error(`Failed to get main branch: ${refResponse.status}`);
  }
  const refData = await refResponse.json() as { object: { sha: string } };
  const baseSha = refData.object.sha;

  // Step 2: Create blob with updated content
  const blobResponse = await fetch(`${apiBase}/git/blobs`, {
    method: 'POST',
    headers,
    body: JSON.stringify({ content: newContent, encoding: 'utf-8' }),
  });
  if (!blobResponse.ok) {
    throw new Error(`Failed to create blob: ${blobResponse.status}`);
  }
  const blobData = await blobResponse.json() as { sha: string };

  // Step 3: Create tree
  const treeResponse = await fetch(`${apiBase}/git/trees`, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      base_tree: baseSha,
      tree: [{ path: filePath, mode: '100644', type: 'blob', sha: blobData.sha }],
    }),
  });
  if (!treeResponse.ok) {
    throw new Error(`Failed to create tree: ${treeResponse.status}`);
  }
  const treeData = await treeResponse.json() as { sha: string };

  // Step 4: Create commit
  const commitMsg = taskNames.length === 1
    ? `fix(roadmap): reset task "${taskNames[0]}"`
    : `fix(roadmap): reset ${taskNames.length} tasks`;
  const commitResponse = await fetch(`${apiBase}/git/commits`, {
    method: 'POST',
    headers,
    body: JSON.stringify({ message: commitMsg, tree: treeData.sha, parents: [baseSha] }),
  });
  if (!commitResponse.ok) {
    throw new Error(`Failed to create commit: ${commitResponse.status}`);
  }
  const commitData = await commitResponse.json() as { sha: string };

  // Step 5: Create branch
  const createRefResponse = await fetch(`${apiBase}/git/refs`, {
    method: 'POST',
    headers,
    body: JSON.stringify({ ref: `refs/heads/${branchName}`, sha: commitData.sha }),
  });
  if (!createRefResponse.ok) {
    throw new Error(`Failed to create branch: ${createRefResponse.status}`);
  }

  // Step 6: Create pull request
  const prBody = `Resetting roadmap tasks:\n${taskNames.map(t => `- [ ] ${t}`).join('\n')}\n\nThese tasks will be picked up by the next \`/orch next\` run.`;
  const prResponse = await fetch(`${apiBase}/pulls`, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      title: commitMsg,
      head: branchName,
      base: 'main',
      body: prBody,
    }),
  });
  if (!prResponse.ok) {
    throw new Error(`Failed to create PR: ${prResponse.status}`);
  }
  const prData = await prResponse.json() as { html_url: string };

  return { prUrl: prData.html_url, branch: branchName };
}

// ============================================================
// REDO MODE — Re-execute a previously completed task
// ============================================================

/**
 * Build the system prompt for /orchestra redo.
 * Like run mode, but instructs the model to treat the specified task
 * as incomplete and re-implement it, regardless of checkbox state.
 */
export function buildRedoPrompt(params: {
  repo: string;
  modelAlias: string;
  previousTasks: OrchestraTask[];
  taskToRedo: string;
}): string {
  const { repo, modelAlias, previousTasks, taskToRedo } = params;
  const [owner, repoName] = repo.split('/');

  let historyContext = '';
  if (previousTasks.length > 0) {
    const recent = previousTasks.slice(-5);
    const lines = recent.map(t => {
      const icon = t.status === 'completed' ? '✅' : t.status === 'failed' ? '❌' : '⏳';
      const pr = t.prUrl ? ` → ${t.prUrl}` : '';
      const sum = t.summary ? ` — ${t.summary.substring(0, 100)}` : '';
      return `  ${icon} [${t.branchName}] "${t.prompt.substring(0, 80)}"${pr}${sum}`;
    });
    historyContext = `\n\n## Recent Orchestra History\n${lines.join('\n')}\n\nThe most recent attempt at this task may have been incorrect. Do NOT repeat the same mistakes.`;
  }

  return `# Orchestra REDO Mode — Re-implement a Task

You are RE-DOING a task that was previously attempted but needs correction.

## Target Repository
- Owner: ${owner}
- Repo: ${repoName}
- Full: ${repo}

## Task to Redo
"${taskToRedo}"

## CRITICAL INSTRUCTIONS
1. This task was previously attempted but the result was INCORRECT or INCOMPLETE.
2. Treat this task as UNCOMPLETED regardless of its checkbox state in the roadmap.
3. Read the EXISTING code carefully to understand what the previous attempt did wrong.
4. Re-implement the task PROPERLY from scratch if needed, or fix the existing attempt.

## Step 1: READ THE ROADMAP
- Use \`github_read_file\` to find and read the roadmap
- Check these paths in order: ${ROADMAP_FILE_CANDIDATES.join(', ')}
- Find the task matching: "${taskToRedo}"
- If the task is marked \`- [x]\`, change it back to \`- [ ]\` in your PR

## Step 2: UNDERSTAND CURRENT STATE
- Use \`github_list_files\` and \`github_read_file\` to examine:
  - The files that were modified by the previous attempt
  - The current state of the code
  - What is wrong or missing
  - Test failures if any

## Step 2.5: REPO HEALTH CHECK
Before re-implementing, check if the target file(s) are too large (>${LARGE_FILE_WARNING_LINES} lines / ~${LARGE_FILE_THRESHOLD_KB}KB of source code).
If so, split the large file into smaller modules FIRST (pure refactor, no behavior change), then proceed with the redo on the now-smaller files.
Use \`github_create_pr\` with ALL files (new modules + updated original) in a SINGLE call — the identifier check allows splits when moved identifiers are found in other files in the same PR.
Update the roadmap to reflect the split as a completed prerequisite task.

## Step 3: RE-IMPLEMENT
- Fix or rewrite the implementation
- Follow existing code conventions
- Include proper types (no \`any\`)
- Write/fix tests if the repo has a test pattern

### How to Edit Existing Files — USE PATCH ACTION
**CRITICAL: Use action \`"patch"\` for all edits to existing files, especially files >100 lines.**

The "patch" action applies surgical find/replace pairs WITHOUT regenerating the whole file:
1. **Read first**: Use \`github_read_file\` to get the exact current content
2. **Identify changes**: Determine the exact text sections that need to change
3. **Use patch action**: \`{"path":"file.js","action":"patch","patches":[{"find":"exact text to find","replace":"replacement text"}]}\`
4. Each "find" must match EXACTLY once — copy text verbatim from the file including whitespace and quotes

This prevents: syntax errors from imperfect regeneration, encoding changes (\u2019 → '), unwanted component rewrites, feature regressions.

Only use \`"update"\` (full content) for: small files (<100 lines), new files ("create"), or changes touching >50% of the file.

### CRITICAL — Surgical Edits Only
**NEVER regenerate or rewrite an entire file from scratch.** This is the most common failure mode.
- Make TARGETED, SURGICAL changes — add/modify/remove only the specific lines needed
- ALL existing exports, functions, classes, and variables MUST be preserved unless the task explicitly requires removing them
- If you cannot make targeted edits, STOP and do a file-splitting refactor first
- The \`github_create_pr\` tool will BLOCK updates that lose more than 60% of original identifiers (unless they moved to other files in the same PR)

### Handle Partial Failures
If you CANNOT complete the redo (file too large, complex dependencies):
1. Still create a PR with WORK_LOG.md update (\`⚠️ partial\` or \`❌ blocked\`)
2. Add a note to ROADMAP.md explaining the blocker (keep task as \`- [ ]\`)
3. Report clearly in ORCHESTRA_RESULT with \`pr: FAILED\` or partial PR URL

## Step 4: UPDATE ROADMAP & WORK LOG
In the SAME PR:

**ROADMAP.md update:**
- Mark the task as \`- [x]\` (completed)
- Add a note: "(redone)" next to the task

**WORK_LOG.md update:**
- Read the existing file first. KEEP ALL existing content BYTE-FOR-BYTE identical.
- APPEND a new row at the bottom matching the EXISTING column format exactly.
- Do NOT restructure the table or change column headers. Fill in columns that match what you have.
- **APPEND ONLY** — NEVER delete or modify existing work log rows (immutable audit trail)

## Step 5: CREATE PR
- Branch: \`redo-{task-slug}-${modelAlias}\` (bot/ prefix added automatically)
- PR title: "fix: redo {task title} [${modelAlias}]"
- PR body: explain what was wrong with the previous attempt and what was fixed, and a footer line: "Generated by: ${modelAlias}"
- Commit messages MUST include the model alias, e.g.: "fix(scope): redo description [${modelAlias}]"

## Step 5.5: VERIFY PR CREATION
**CRITICAL** — After calling \`github_create_pr\`, CHECK THE TOOL RESULT:
- If it returned a PR URL (https://github.com/...) → success, proceed to Step 6
- If it returned an error (422, 403, etc.) → FIX AND RETRY with a different branch name
- **NEVER claim you created a PR if the tool returned an error.**

## Step 6: REPORT
\`\`\`
ORCHESTRA_RESULT:
branch: {branch-name}
pr: {pr-url}
files: {comma-separated list of changed files}
summary: {what was wrong and how it was fixed}
\`\`\`

The \`pr:\` field MUST be a real GitHub URL. If PR creation failed, set \`pr: FAILED\` and explain in the summary.

## Rules
- Always create a PR — never just describe what should be done
- Focus on FIXING the previous attempt, not starting from zero (unless necessary)
- ALWAYS update ROADMAP.md and WORK_LOG.md in the same PR
- Do NOT modify unrelated files
- **NEVER regenerate entire files** — make surgical, targeted edits only. Preserve all existing functions, exports, and business logic.
- **NEVER delete work log entries** — WORK_LOG.md is append-only. The tool will BLOCK deletion of existing rows.
- **NEVER delete roadmap tasks** — mark them [x] or add notes, but never remove entries. The tool will BLOCK this.
${historyContext}`;
}

// === Orchestra Event Observability ===

/** Lightweight event for R2-persisted orchestra observability. */
export interface OrchestraEvent {
  timestamp: number;
  taskId: string;
  userId?: string;
  modelAlias: string;
  eventType: 'stall_abort' | 'validation_fail' | 'task_abort' | 'task_complete' | 'deliverable_retry';
  details: Record<string, unknown>;
}

const MAX_EVENTS_PER_MONTH = 500;

/**
 * Append an orchestra event to R2 (monthly JSONL bucket).
 * Non-blocking: catches errors internally, never throws.
 */
export async function appendOrchestraEvent(
  r2: R2Bucket,
  event: OrchestraEvent,
): Promise<void> {
  const date = new Date(event.timestamp);
  const month = `${date.getUTCFullYear()}-${String(date.getUTCMonth() + 1).padStart(2, '0')}`;
  const key = `orchestra-events/${month}.jsonl`;

  try {
    let lines: string[] = [];
    const existing = await r2.get(key);
    if (existing) {
      const text = await existing.text();
      lines = text.split('\n').filter(l => l.trim());
    }
    lines.push(JSON.stringify(event));
    if (lines.length > MAX_EVENTS_PER_MONTH) {
      lines = lines.slice(-MAX_EVENTS_PER_MONTH);
    }
    await r2.put(key, lines.join('\n') + '\n');
  } catch (err) {
    console.error('[OrchestraEvents] Failed to append event:', err);
  }
}

/**
 * Load recent orchestra events from R2 (last N months).
 * Returns events sorted newest-first.
 */
export async function getRecentOrchestraEvents(
  r2: R2Bucket,
  monthsBack: number = 2,
  modelFilter?: string,
  limit: number = 100,
): Promise<OrchestraEvent[]> {
  const events: OrchestraEvent[] = [];
  const now = new Date();

  for (let i = 0; i < monthsBack; i++) {
    const d = new Date(now.getFullYear(), now.getMonth() - i, 1);
    const month = `${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, '0')}`;
    const key = `orchestra-events/${month}.jsonl`;

    try {
      const obj = await r2.get(key);
      if (!obj) continue;
      const text = await obj.text();
      for (const line of text.split('\n')) {
        if (!line.trim()) continue;
        try {
          const ev = JSON.parse(line) as OrchestraEvent;
          if (modelFilter && ev.modelAlias !== modelFilter) continue;
          events.push(ev);
        } catch { /* skip malformed lines */ }
      }
    } catch { /* skip missing months */ }
  }

  events.sort((a, b) => b.timestamp - a.timestamp);
  return events.slice(0, limit);
}

/**
 * Aggregate orchestra event stats for display.
 */
export function aggregateOrchestraStats(events: OrchestraEvent[]): {
  total: number;
  byType: Record<string, number>;
  byModel: Record<string, { total: number; completions: number; failures: number }>;
} {
  const byType: Record<string, number> = {};
  const byModel: Record<string, { total: number; completions: number; failures: number }> = {};

  for (const ev of events) {
    byType[ev.eventType] = (byType[ev.eventType] || 0) + 1;

    if (!byModel[ev.modelAlias]) {
      byModel[ev.modelAlias] = { total: 0, completions: 0, failures: 0 };
    }
    byModel[ev.modelAlias].total++;
    if (ev.eventType === 'task_complete') {
      byModel[ev.modelAlias].completions++;
    } else if (ev.eventType === 'stall_abort' || ev.eventType === 'task_abort') {
      byModel[ev.modelAlias].failures++;
    }
  }

  return { total: events.length, byType, byModel };
}
