import { describe, it, expect } from 'vitest';
import { parseSpecMarkdown, generatePRBody, slugify } from './spec-parser';

const SAMPLE_SPEC = `# Mobile UX Improvements

## Overview
Improve the mobile experience for the application with responsive layouts and touch-friendly interactions.

## Requirements
- Add responsive breakpoints for mobile screens
- Implement swipe gestures for navigation
- Optimize image loading for mobile bandwidth

## API Routes
- GET /api/mobile/config — mobile-specific settings
- POST /api/mobile/analytics — track mobile events

## Database Changes
- Add mobile_sessions table
- Add device_type column to users table

## UI Components
- MobileNavbar component
- SwipeableCard component
- BottomSheet modal

## Notes
This is a Phase 2 feature.
`;

describe('parseSpecMarkdown', () => {
  it('should extract the title from the first heading', () => {
    const parsed = parseSpecMarkdown(SAMPLE_SPEC);
    expect(parsed.title).toBe('Mobile UX Improvements');
  });

  it('should extract overview text', () => {
    const parsed = parseSpecMarkdown(SAMPLE_SPEC);
    expect(parsed.overview).toContain('mobile experience');
  });

  it('should extract requirements as bullet points', () => {
    const parsed = parseSpecMarkdown(SAMPLE_SPEC);
    expect(parsed.requirements).toHaveLength(3);
    expect(parsed.requirements[0]).toContain('responsive breakpoints');
    expect(parsed.requirements[1]).toContain('swipe gestures');
    expect(parsed.requirements[2]).toContain('image loading');
  });

  it('should extract API routes', () => {
    const parsed = parseSpecMarkdown(SAMPLE_SPEC);
    expect(parsed.apiRoutes).toHaveLength(2);
    expect(parsed.apiRoutes[0]).toContain('/api/mobile/config');
    expect(parsed.apiRoutes[1]).toContain('/api/mobile/analytics');
  });

  it('should extract database changes', () => {
    const parsed = parseSpecMarkdown(SAMPLE_SPEC);
    expect(parsed.dbChanges).toHaveLength(2);
    expect(parsed.dbChanges[0]).toContain('mobile_sessions');
  });

  it('should extract UI components', () => {
    const parsed = parseSpecMarkdown(SAMPLE_SPEC);
    expect(parsed.uiComponents).toHaveLength(3);
    expect(parsed.uiComponents[0]).toContain('MobileNavbar');
  });

  it('should preserve raw sections', () => {
    const parsed = parseSpecMarkdown(SAMPLE_SPEC);
    expect(parsed.rawSections).toHaveProperty('notes');
    expect(parsed.rawSections['notes']).toContain('Phase 2');
  });

  it('should handle minimal spec with just a title', () => {
    const parsed = parseSpecMarkdown('# Simple Feature\n\nJust a description.');
    expect(parsed.title).toBe('Simple Feature');
    expect(parsed.requirements).toHaveLength(0);
    expect(parsed.apiRoutes).toHaveLength(0);
  });

  it('should handle spec with no heading', () => {
    const parsed = parseSpecMarkdown('Some content without a heading');
    expect(parsed.title).toBe('Untitled Spec');
  });

  it('should handle numbered lists', () => {
    const spec = `# Test
## Requirements
1. First requirement
2. Second requirement
3. Third requirement
`;
    const parsed = parseSpecMarkdown(spec);
    expect(parsed.requirements).toHaveLength(3);
    expect(parsed.requirements[0]).toBe('First requirement');
  });
});

describe('generatePRBody', () => {
  it('should generate a PR body with spec info', () => {
    const parsed = parseSpecMarkdown(SAMPLE_SPEC);
    const body = generatePRBody(parsed, ['src/routes/config.ts', 'src/components/navbar.tsx']);
    expect(body).toContain('Dream Machine Build');
    expect(body).toContain('Mobile UX Improvements');
    expect(body).toContain('src/routes/config.ts');
    expect(body).toContain('Generated by Dream Machine');
  });

  it('should include requirements', () => {
    const parsed = parseSpecMarkdown(SAMPLE_SPEC);
    const body = generatePRBody(parsed, []);
    expect(body).toContain('responsive breakpoints');
  });
});

describe('slugify', () => {
  it('should convert to lowercase kebab-case', () => {
    expect(slugify('Mobile UX Improvements')).toBe('mobile-ux-improvements');
  });

  it('should remove special characters', () => {
    expect(slugify('Hello, World! (v2)')).toBe('hello-world-v2');
  });

  it('should truncate to 50 chars', () => {
    const long = 'a'.repeat(100);
    expect(slugify(long).length).toBeLessThanOrEqual(50);
  });

  it('should handle empty string', () => {
    expect(slugify('')).toBe('');
  });

  it('should remove leading/trailing dashes', () => {
    expect(slugify('---hello---')).toBe('hello');
  });
});
